/** @format */

import Head from "next/head";
import styles from "./Layout.module.css";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>{children}</main>
      <footer className={styles.footer}>
        <p>
          Made by
          <a href="https://valenciahq.com/" target="_blank" rel="noreferrer">
            ValenciaHQ
          </a>
        </p>
      </footer>
    </>
  );
}
